export function OptimizerPanel() {
  return <section id="optimizer-panel" className="app-panel optimizer-panel" data-app-panel="optimizer" hidden>
    <section className="optimizer-toolbar card">
      <div className="folder-actions"><button id="optimizer-choose-input" className="button primary" data-i18n-title="optimizer.chooseInput"><span className="button-icon icon-folder" aria-hidden="true" /><span className="button-label" data-i18n="optimizer.chooseInput">Abrir carpeta censurada</span></button><button id="optimizer-choose-output" className="button secondary" data-i18n-title="optimizer.chooseOutput" disabled><span className="button-icon icon-folder-arrow" aria-hidden="true" /><span className="button-label" data-i18n="optimizer.chooseOutput">Carpeta optimizada</span></button><div className="folder-text"><strong id="optimizer-input-name" data-i18n="optimizer.inputEmpty">Ninguna carpeta seleccionada</strong><span id="optimizer-output-name" data-i18n="optimizer.outputEmpty">Se guardarán en la subcarpeta optimized si no eliges salida</span></div></div>
      <div className="toolbar-status-strip" aria-hidden="true"><span className="status-online">▮ LOCAL</span><span data-i18n="optimizer.statusReady">OPTIMIZER READY</span></div>
      <div className="toolbar-actions"><button id="optimizer-process" className="button secondary" data-i18n-title="optimizer.process" disabled><span className="button-icon icon-radar" aria-hidden="true" /><span className="button-label" data-i18n="optimizer.process">Optimizar imágenes</span></button><button id="optimizer-save-all" className="button accent" data-i18n-title="optimizer.saveAll" disabled><span className="button-icon icon-floppy" aria-hidden="true" /><span className="button-label" data-i18n="optimizer.saveAll">Guardar optimizadas</span></button></div>
    </section>
    <section id="optimizer-notice" className="notice hidden" />
    <div className="optimizer-layout">
      <aside className="optimizer-queue card"><div className="panel-heading"><div><span className="eyebrow" data-i18n="optimizer.eyebrow">OPTIMIZADOR</span><h2 data-i18n="optimizer.queueTitle">Imágenes censuradas</h2></div><span id="optimizer-count" className="count-badge">0</span></div><div id="optimizer-file-list" className="queue-list empty-state" data-i18n="optimizer.empty">Selecciona una carpeta para comenzar</div></aside>
      <section className="optimizer-preview card"><div className="review-head"><div><span className="eyebrow" data-i18n="optimizer.previewEyebrow">VISTA PREVIA</span><h2 id="optimizer-current-name" data-i18n="optimizer.previewEmpty">Selecciona una imagen</h2></div><span id="optimizer-current-index">—</span></div><div className="optimizer-preview-grid"><div className="optimizer-preview-frame"><span data-i18n="optimizer.original">ORIGINAL</span><canvas id="optimizer-original-preview" hidden /></div><div className="optimizer-preview-frame"><span data-i18n="optimizer.optimized">OPTIMIZADA</span><canvas id="optimizer-optimized-preview" hidden /><div id="optimizer-empty-preview" className="empty-state" data-i18n="optimizer.previewHint">Pulsa optimizar para ver el resultado</div></div></div><div className="optimizer-stats"><div><span data-i18n="optimizer.originalSize">Original</span><strong id="optimizer-original-size">—</strong></div><div><span data-i18n="optimizer.optimizedSize">Optimizada</span><strong id="optimizer-optimized-size">—</strong></div><div><span data-i18n="optimizer.reduction">Reducción</span><strong id="optimizer-reduction">—</strong></div></div></section>
      <aside className="optimizer-settings card"><div className="panel-heading"><div><h2 data-i18n="optimizer.settingsTitle">OPTIMIZACIÓN</h2></div><span className="selection-badge">✦</span></div><div className="settings-body"><label className="field-label" htmlFor="optimizer-format" data-i18n="optimizer.format">Formato de salida</label><select id="optimizer-format" className="select"><option value="original" data-i18n="optimizer.formatOriginal">Conservar formato</option><option value="webp" data-i18n="optimizer.formatWebp">WebP · recomendado</option><option value="jpeg" data-i18n="optimizer.formatJpeg">JPEG</option><option value="png" data-i18n="optimizer.formatPng">PNG · sin pérdida</option></select><div className="field-row"><label className="field-label" htmlFor="optimizer-quality" data-i18n="optimizer.quality">Calidad visual</label><output id="optimizer-quality-value">92%</output></div><input id="optimizer-quality" type="range" min="70" max="100" value="92" /><label className="optimizer-check"><input id="optimizer-lossless" type="checkbox" /><span data-i18n="optimizer.lossless">Modo sin pérdida</span></label><p className="help" data-i18n="optimizer.qualityHint">PNG conserva cada píxel. WebP y JPEG reducen mucho el peso con calidad visual alta.</p><div className="divider" /><div className="optimizer-detail"><span data-i18n="optimizer.dimensions">Dimensiones</span><strong id="optimizer-dimensions">—</strong></div><p className="help" data-i18n="optimizer.localHint">Todo el proceso ocurre localmente y los originales no se modifican.</p></div></aside>
    </div>
  </section>;
}
